//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernDesign.MVVM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class chitatelskii_bilet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public chitatelskii_bilet()
        {
            this.kartoteka_chitatel = new HashSet<kartoteka_chitatel>();
        }
    
        public int id_chit_bileta { get; set; }
        public string FIO { get; set; }
        public string Adress { get; set; }
        public string Rapochii_tel { get; set; }
        public string Domachnii_tel { get; set; }
        public Nullable<System.DateTime> Data_rozhdenia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kartoteka_chitatel> kartoteka_chitatel { get; set; }
    }
}
