//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernDesign.MVVM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class examplar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public examplar()
        {
            this.kartoteka_chitatel = new HashSet<kartoteka_chitatel>();
            this.vkladish = new HashSet<vkladish>();
        }
    
        public int id_exemplar { get; set; }
        public Nullable<int> id_book { get; set; }
        public string mesto_razmeshenia_v_biblioteke { get; set; }
    
        public virtual books books { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kartoteka_chitatel> kartoteka_chitatel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vkladish> vkladish { get; set; }
    }
}
