//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernDesign.MVVM.Model
{
    using ModernDesign.Core;
    using System;
    using System.Collections.Generic;
    using System.Windows;


    public partial class kartoteka_chitatel: ObservableObject
    {
        public Nullable<System.DateTime> date_vozvrat_book { get; set; }
        public System.DateTime date_vidachi_book { get; set; }
        public Nullable<int> id_chitatelskii_bilet { get; set; }
        public Nullable<int> id_exemplar { get; set; }
        public Nullable<int> id_personal { get; set; }
    
        public virtual chitatelskii_bilet chitatelskii_bilet { get; set; }
        public virtual examplar examplar { get; set; }
        public virtual Personal Personal { get; set; }
        public Nullable<System.DateTime> dateVozvratNotified
        {
            get
            {
                return date_vozvrat_book;
            }
            set
            {
                date_vozvrat_book = value;
                OnPropertyChanged(nameof(dateVozvratNotified));
            }
        }        
    }
}
